### ISSUE TITLE
Spatial dimension sanity check

### ISSUE THREAD

**Issue by dmay23** [TEAR-ERC/tandem#27]
The default compilation uses `-DDOMAIN_DIMENSION=2` i.e. the code base assumes the spatial dimension is 2. 

If you load a GMSH file defining tets, the z coord will be set to zero (and the FE implementation will produce singular matrices). To avoid confusion, I suggest some sanity checking / error checking is performed when loading a mesh file.

For example, 
[1] If `-DDOMAIN_DIMENSION=2` and no triangles are parsed -> error.
[2] If `-DDOMAIN_DIMENSION=3` and no tets are parsed -> error

That should catch most use cases with current use cases of tandem.

**Comment by uphoffc** [comment]
I added a few simple sanity checks. When you load a 3D mesh in 2D you'll get:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  GMSH element of type 4 is not a 0,...,2-simplex. Does the domain dimension match the dimension of the mesh?
```
When you load a 2D mesh in 3D you'll get:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  The mesh does not contain any 3-simplex. Does the domain dimension match the dimension of the mesh?
```
