### ISSUE TITLE
Specification of output path

### ISSUE THREAD

**Issue by dmay23** [TEAR-ERC/tandem#34]
With checkpointing and VTK output, SEAS models potentially generate a lot of heavy data which should not be written into the directory where the model is run. 

It would make sense to introduce a new toml parameter which specifies the output path. All output generated should be written into this location.

For checkpointed data, it would make sense to write these files in special location. 
Something like this 
```
{OUTPUT_PATH}/checkpoint/{SCENARIO_NAME}/
```
This would make sense as I believe that now all SEAS models need to define a scenario name and different scenarios would generally imply different model parameters resulting in different time histories / trajectories for the time solve (TS) and different green's functions.

**Comment by uphoffc** [comment]
For the vtk output you can already select different folders. Just add the
```toml
prefix="/path/to/output/scenario"
```

**Comment by dmay23** [comment]
Nice. Does the path have to already exist or will it be created (recursively if required) by tandem?

**Comment by uphoffc** [comment]
No it must exist.

**Comment by dmay23** [comment]
I guess for the probes you change this
```
prefix = "fltst_"
```
to this
```
prefix = "/path/to/output/fltst_"
```
?

**Comment by uphoffc** [comment]
Yes

**Comment by dmay23** [comment]
Okay. So I see in `SeasConfig.cpp` there is support to parse `prefix`. That is great.

As a side note: For the end-user, waiting in a queue for days, only to have the job abort because you forgot to create the directory is annoying and frustrating. We should add support to create the directories.
