### ISSUE TITLE
Inconsistent displacement in domain output when using the branch dmay/seas-checkpoint-greenfunc

### ISSUE THREAD

**Issue by daisy20170101** [TEAR-ERC/tandem#42]
Hi, there is an error in the domain output using the branch dmay/seas-checkpoint-greenfunc. The displacement u0 remains constant over time as Vpl, instead of Vpl*t, before any coseismic event.  While the calculation of fault slip rate and stresses are correct, compared to the main branch. 

![gfs-branch-loading](https://user-images.githubusercontent.com/33549997/224644494-a7f4fc1e-f71e-4af4-92a0-8cf00c86ca44.jpeg)

![compare](https://user-images.githubusercontent.com/33549997/224645560-5e8ee3c6-e9cd-49c6-b57b-8c7dad902b13.png)

**Comment by Thomas-Ulrich** [comment]
Can you give me more details about how I can reproduce the issue? (I even don't get a u0 output, only a u)

**Comment by daisy20170101** [comment]
i put the setup here: /import/freenas-m-05-seissol/dli/Shared/inplane

**Comment by Thomas-Ulrich** [comment]
I've tested the setup with green functions calculated, and with green functions loaded, and u0 and u1 vary over time as expected.
